@baseUrl = https://ereport.local/api/v1
@baseUrl = http://localhost:8085/api/v1
@token = grsosr7ov6mmt84k5m1av95od2

### Satker (Form Add/Edit)
POST {{baseUrl}}/ereport/satker/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

# id=54TYD
id=

### Satker (List)
POST {{baseUrl}}/ereport/satker/list
token: {{token}}
Content-Type: application/x-www-form-urlencoded

page=1&size=10&cari=&group=

### Satker (Save)
POST {{baseUrl}}/ereport/satker/save
token: {{token}}
Content-Type: application/x-www-form-urlencoded

# id_satker=54TYD&nama_satker=Polresta Pontianak Kota&group_satker=&password=ereport
# id_satker=H9XOF&nama_satker=Polsek Pontianak Barat&group_satker=54TYD&password=ereport
# id_satker=UFZHT&nama_satker=Polsek Pontianak Selatan&group_satker=54TYD&password=ereport
# id_satker=7QXVP&nama_satker=Polresta Singkawang&group_satker=&password=ereport
# id_satker=Q15SC&nama_satker=Polsek Singkawang Barat&group_satker=7QXVP&password=ereport
# id_satker=SLGDB&nama_satker=Polsek Singkawang Tengah&group_satker=7QXVP&password=ereport
# id_satker=2L8J1&nama_satker=Polresta Landak&group_satker=&password=ereport
# id_satker=N8K8V&nama_satker=Polsek Sebangki&group_satker=2L8J1&password=ereport
# id_satker=WRMUH&nama_satker=Polsek Ngabang&group_satker=2L8J1&password=ereport


### Form Cek Tahanan
POST {{baseUrl}}/ereport/tahanan/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

satker=""


### Send Multipart
POST {{baseUrl}}/ereport
token: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="id"

xxx
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./upload/default/no-user-female.png
--WebKitFormBoundary7MA4YWxkTrZu0gW--