@baseUrl = https://ereport.local/api/v1
@baseUrl = http://localhost:8085/api/v1
@token = grsosr7ov6mmt84k5m1av95od2

### Satker (Form Add/Edit)
POST {{baseUrl}}/ereport/satker/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

id=54TYD

### Satker (List)
POST {{baseUrl}}/ereport/satker/list
token: {{token}}
Content-Type: application/x-www-form-urlencoded

page=1&cari=&group=

### Satker (Save)
POST {{baseUrl}}/ereport/satker/save
token: {{token}}
Content-Type: application/x-www-form-urlencoded

id_satker=54TYD&nama_satker=Polresta Pontianak Kota&group_satker=&password=ereport















### Form Cek Tahanan
POST {{baseUrl}}/ereport/tahanan/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

satker=""


### Send Multipart
POST {{baseUrl}}/ereport
token: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="id"

xxx
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./upload/default/no-user-female.png
--WebKitFormBoundary7MA4YWxkTrZu0gW--